[package]
name = "image-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
clap = {version = "2.34", features = ["yaml"]}
text_io = "0.1.9"